### PR TITLE
Update add-a-database.md

### PR DESCRIPTION
**Pull request by davericher**
Provide a more sensible configuration that allows the original defaults for Laravel to continue working when running application outside of Nanobox.

### CODE REVIEW

**Review by sanderson — CHANGES_REQUESTED** [review]
Thanks for this. Some quick notes.

Nanobox doesn't auto-generate an environment variable for the database port. Since every database is given a unique virtual IP, Nanobox will always use the default port for the service. In this case, 3306 for MySQL.

There's been a few pull requests submitted for the database configuration and we've gone back and forth on what it should be. The nested `env()` function method has been suggested before but there was some push back from the community. They weren't huge fans of the nested function. I'm fine with it. I just want to make sure we're going with whatever the Laravel community expects/likes.

**Comment by danhunsaker** [comment]
One could argue that if a user is building with Nanobox, they aren't deploying to Laravel Forge (which isn't compatible with Nanobox deploys anyway), so wouldn't need the defaults anyway.

One could also argue that the original developer may use one deployment target, while other developers, especially on open source projects with many users, might deploy to other targets, so supporting as many as feasible is best practice.

I suspect the main concern about nesting functions in the `.env` is one of performance - these functions will be called every page load, so that's request overhead which could be avoided by using strings instead, or at most a single function call to translate existing env vars. Perhaps some way to "compile" the `.env` during deploy would appease these users - a script that evaluates each KEY=value pair and rewrites the file to use string values instead of function calls at all (since the environment won't change after deploy).

In the meantime, this is a highly sensible default recommendation for most projects, especially in development phases. (The port value is useful to mention for those who prefer to run their DB outside the app itself for whatever reason [I still don't see the benefit, generally speaking, of doing so, but many others do, so *shrug*], though one could just set `DB_PORT` in these cases...)

**Comment by davericher** [comment]
I think you are over estimaiting the additional calls. You could provide two config blocks. One for dev. One for release. This is the dev version in my mind. Personally I am loving nanobox by making a file break something unless used in nanobox seems counter productive

**Comment by danhunsaker** [comment]
To be clear, I'm not in the "too much overhead" camp, though PHP 5.x is notorious for function calls having excessive overhead.  It's just my best guess as to the reason nested calls were argued against.

**Review by sanderson — APPROVED** [review]
Thanks. I'm fine with the nested env() functions. I'll go ahead and approve the PR and let anybody else who wants to weigh in.

**Pull request merged**
