### PR TITLE
updated nette guide

### PR DESCRIPTION
**Pull request by foxycode**

### CODE REVIEW

**Comment by tylerflint** [comment]
@foxycode This looks perfect! Very nice work.

@sdomino or @sanderson I'll let you guys review and merge, but it looks great to me.

**Comment by sdomino** [comment]
@foxycode this looks great. I'll go ahead and merge and make the guides accessible. Don't forget to let me know when you're ready for a fork of your quickstart ;). Thanks!

**Comment by foxycode** [comment]
Don't make this pages public yet please. I found some issues in them. Will have more time for this and quickstart app on weekend.

**Comment by sdomino** [comment]
Sounds good. I'll hold off for now. Just let me know

**Pull request merged**
